joint_limits:
  panda_joint1:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0
  panda_joint2:
    has_position_limits: true
    min_position: -1.2
    max_position: 1.76
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0
  panda_joint3:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0
  panda_joint4:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0
  panda_joint5:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0
  panda_joint6:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0
  panda_joint7:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0

  panda_finger_joint1:
    has_velocity_limits: true
    max_velocity: 0.2
  panda_finger_joint2:
    has_velocity_limits: true
    max_velocity: 0.2
